version: '3.4'
services:
  kubegame-nodeJS:
    image: node:15.14.0-stretch
    user: node
    working_dir: /home/node/app
    environment:
      - NODE_ENV=production
    volumes:
      - ./app:/home/node/app
    ports:
      - 80:3000
    command: npm start